### ISSUE TITLE
Orthographic profiles

### ISSUE THREAD

**Issue by tresoldi** [lexibank/wold#4]
All languages are missing orthographic profiles; in some cases it should be easy to add (forms are already in IPA or almost-IPA), other not so much.

**Comment by LinguList** [comment]
A list of positive languages should be easy to make, as well as a single orthoprofile for these. Then, this could be applied, and data could be segmented, even within the tokenize-function (which takes the item as argument, so should retrieve info about the row content). In this way, segmentable data could indeed be segmented!

**Comment by tresoldi** [comment]
Yes, it is pretty much the workflow we are thinking. We will start working on this tomorrow.

**Comment by tresoldi** [comment]
We have finished the profiles for all 41 languages (English and Dutch using data from CELEX, manually corrected/complemented by me; @natalia-morozova took care of all the others). The individual profiles are here: https://github.com/natalia-morozova/wold/tree/master/individual

I started updating `lexibank_wold.py`, but found out that the `LANGUAGES` field is only informative, and `segments.Tokenizer` does not actually support multiple doculects in a single profile. It even complains about duplicate graphemes when there are no in-doculect duplicates, as when loading https://github.com/natalia-morozova/wold/blob/master/etc/orthography.tsv

As a solution that does not involve changes to `segments` or `pylexibank`, I suggest to load the individual profiles at the beginning of `cmd_install()` and override the `.tokenizer()` method so that it uses the appropriate, already in memory, individual profile. What is your opinion? Pinging @LinguList @xrotwang @SimonGreenhill

**Comment by LinguList** [comment]
An easy way may be to organize the IPA per language as a column of `orthography.tsv`, thus, instead of "ipa" you have `German`, `English`, etc.

Then you can load the profile as usual, but you can use it with the language as keywords:

```profile(SEQ, column='German')```

Then, you can proceed as you want. I would recommend that you use the new freedom and make an explicit splitting and segmentation in a loop, adding all forms with 

```ds.add_form_with_segments```

specifically in the first phase of adjusting this.

**Comment by tresoldi** [comment]
Unfortunately the multi-column solution does not seem to work... The profiler assumes that each grapheme will have a corresponding transformation in all doculects, which is not true, and empty correspondences end up as deletions.

For example, in Takia `"a"` and `"n"` are always transformed into IPA `a` and `n` (they never form a complex grapheme), so that the only entries we have involving them are those for the individual character match. However, in other languages we do have the `"an"` grapheme, transformed into various IPA sequences such as /ã/ or /aŋ/. If I only collect the global list of graphemes and fill it with the corresponding transform when available (as in https://github.com/natalia-morozova/wold/blob/master/etc/orthography.tsv ), the tokenization fails, with strings such as `"tan"` in Takia transformed into /t/ because the `"an"` grapheme is empty for this given language.

A theoretical alternative would be to collect all the global graphemes and tokenize those which are missing in each language, making sure no cell is empty, but besides adding complexity this would still result in erroneous tokenizations, as we would be creating artificial contexts that were originally intended. Changing `segments` is not an option, as it would introduce incompatibilities.

**Comment by LinguList** [comment]
Of course, it fails, what you have to do is transform `an` into `a n` in all cases where it is not listed.

**Comment by LinguList** [comment]
I'd first try this way. But if it does not work, nothing speaks against:

1. explicitly loading profiles, adn also sgmenting data, without overriding anything lexibank internal through the class hierarchy (which is difficult to debug), given that you can add segments explicitly now 
2. segment the data in wold beforehand and load the list from explicit mappings, again adding explicit segments for each form (nothing speaks against that, again, because you can treat this as amanual segmentation, which I also do in my data on Chinese dialects,where I segmented data intedpendently).

So isntead of searching for complicated solutions, I suggest to just be pragmatic here: what we want is the segmentation, adding it is possible in many different ways, but itisnot that important. Important is the result.

**Comment by SimonGreenhill** [comment]
Hmm. This is awesome to have WOLD mapped like this, thanks @tresoldi and @natalia-morozova! 

The profile loading, however, is annoying, I think a lot of datasets are likely to have per-language or per-subset orthographies. Can we work around this by a rule like: "if there is a column <language> then any mapping that has a non-empty <language> is only for that language, otherwise it applies to everything".

**Comment by LinguList** [comment]
I think, instead of looking too much into workarounds, it is better to either add support for multi-language profiles, which is going to take a longer time, as it is complicated, how they would be instantiated, etc. OR to use a simple workaround, by adding multiple profiles to `etc/`, as I mentioned before, loading them, one by one, with `segments` package, and doing the segmentation explicitly in the loop. In this way, we also finally see the profiles in action and can use this example, potentially some more, to find the best solution for multi-profiles in the future. While the solution of the `an` is possible, as indicated by me above, it is also dangerous, as it increases complexity, and decreases maintainability. So it may really be better to just write some clear code that does the things explicitly now, without thinking much how to do this IN lexibank, but rather use this as our starting point to discuss how we should add this functionality to lexibank.

**Comment by SimonGreenhill** [comment]
Agree! I was arguing for the same thing, just with one file. But I think one file per language is a better idea (profiles tend to be quite long  and this is easier to debug etc). Let's fix this and do it properly as we're going tohave this problem in future again.

**Comment by LinguList** [comment]
I have been working a bit on single-language profiles with Nathan in the past. My experience is: single-language is much easier to handle, than multiple languages with the column solution (and @tresoldi and @natalia-morozova were also doing this in this way), so going for one-file-per-language (or per set of languages, e.g., per source, think of ABVD) seems like the natural solution we need to face at some point.

**Comment by SimonGreenhill** [comment]
Yes, I think @xrotwang suggested profiles.csv which contains language:profile.prf mappings, then we can handle 1:1 or 1:n situations by reading the profiles.csv.

**Comment by LinguList** [comment]
Yes, sounds very good. So @tresoldi, to make it easier for us to follow, and e.g, for @xrotwang or one of us to add lexibank-code to account for this, please prepare an explicit segmentation, without modifying lexibank code, where you already maybe have a profiles.csv in `etc/` where you read in theinformation for the mappings, and then do the rest by using the `segments` package (but please check with lexibank's defaults for segments here, as they differ from vanilla-segments).

**Comment by tresoldi** [comment]
Great, I'll do it.

**Comment by SimonGreenhill** [comment]
Thanks @tresoldi !

**Comment by tresoldi** [comment]
Ok, the approach works perfectly. So much that I was able to list a number of things to fix, but we are getting there (67 BIPA errors on ~64k lexemes, ~365k tokens).

**Comment by SimonGreenhill** [comment]
0.1 % error rate... terrible :)

**Comment by tresoldi** [comment]
There still phonological and coding work to do and I am calling the day on that, but if you want to start playing, I've pushed the CLDF: https://github.com/natalia-morozova/wold/tree/master/cldf

**Comment by LinguList** [comment]
could you please already push the code to the official repo? just make a test fork of wold, so we can see it directly already thanks!

**Comment by tresoldi** [comment]
I am still working on the code, I am doing some of the normal tasks by hand (to understand more clearly what is needed) so that later I can use the standard resources as much as possible. I plan to get back to it tomorrow and do the PR before my holidays, but the current code is in Natalia's repository: https://github.com/natalia-morozova/wold/blob/master/lexibank_wold.py

Just don't judge as a PR what is not a PR yet, please. :wink:

**Comment by tresoldi** [comment]
But even if I don't finish by this weekend, I'll move to a branch in the official repo, also removing the temporary files that were there during development. :+1:

**Comment by LinguList** [comment]
Just for practicality reasons, as @xrotwang taught me: if you want to share code and have others look at it, it best to already pass it on a branch of the github repo. So I'll wait until itis there before I comment on this, since I prefer to be able to run the code instead of commenting in the blind. But take your time, and many thanks to you both for the work!

**Comment by tresoldi** [comment]
PR at https://github.com/lexibank/wold/pull/6
